import presentation_layer.assets.ressources_rc
# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 720)
        MainWindow.setStyleSheet("border: 5px solid black; \n"
"background-color: black;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("border: none;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setStyleSheet("background:#0F1C1F;\n"
"border: none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.htw_logo = QtWidgets.QLabel(parent=self.page_1)
        self.htw_logo.setGeometry(QtCore.QRect(70, 0, 661, 181))
        self.htw_logo.setObjectName("htw_logo")
        self.tracking_system_logo = QtWidgets.QLabel(parent=self.page_1)
        self.tracking_system_logo.setGeometry(QtCore.QRect(170, 50, 481, 501))
        self.tracking_system_logo.setObjectName("tracking_system_logo")
        self.tracking_system_text = QtWidgets.QLabel(parent=self.page_1)
        self.tracking_system_text.setGeometry(QtCore.QRect(70, 450, 531, 81))
        self.tracking_system_text.setStyleSheet("color: #E8E8E8;\n"
"font-family:Arial,sans-serif;\n"
" font-style: italic; \n"
"font-weight: bold;\n"
"text-decoration: none; \n"
"font-size: 32pt")
        self.tracking_system_text.setObjectName("tracking_system_text")
        self.developerLabel = QtWidgets.QLabel(parent=self.page_1)
        self.developerLabel.setGeometry(QtCore.QRect(10, 650, 111, 61))
        self.developerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.developerLabel.setObjectName("developerLabel")
        self.start_button = QtWidgets.QPushButton(parent=self.page_1)
        self.start_button.setGeometry(QtCore.QRect(260, 590, 171, 51))
        self.start_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #76B800;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #8CD800;  /* Lighter green for hover */\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #4A9B00;  /* Adjusted pressed color to a darker green */\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 25px;  /* Ensure the disabled state also has the same curvy effect */\n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.start_button.setObjectName("start_button")
        self.tracking_system_logo.raise_()
        self.htw_logo.raise_()
        self.tracking_system_text.raise_()
        self.developerLabel.raise_()
        self.start_button.raise_()
        self.stackedWidget.addWidget(self.page_1)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.tracking_system_text_4 = QtWidgets.QLabel(parent=self.page_4)
        self.tracking_system_text_4.setGeometry(QtCore.QRect(80, 0, 541, 81))
        self.tracking_system_text_4.setStyleSheet("color: #E8E8E8;\n"
"font-family:Arial,sans-serif;\n"
" font-style: italic; \n"
"font-weight: bold;\n"
"text-decoration: none; \n"
"font-size: 32pt")
        self.tracking_system_text_4.setObjectName("tracking_system_text_4")
        self.label_7 = QtWidgets.QLabel(parent=self.page_4)
        self.label_7.setGeometry(QtCore.QRect(10, 650, 101, 51))
        self.label_7.setObjectName("label_7")
        self.back_button_2 = QtWidgets.QPushButton(parent=self.page_4)
        self.back_button_2.setGeometry(QtCore.QRect(170, 570, 171, 61))
        self.back_button_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #404040;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(112,0,0);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.back_button_2.setObjectName("back_button_2")
        self.home_button = QtWidgets.QPushButton(parent=self.page_4)
        self.home_button.setGeometry(QtCore.QRect(360, 570, 171, 61))
        self.home_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #76B800;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #8CD800;  /* Lighter green for hover */\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #4A9B00;  /* Adjusted pressed color to a darker green */\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 25px;  /* Ensure the disabled state also has the same curvy effect */\n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.home_button.setObjectName("home_button")
        self.output_label = QtWidgets.QLabel(parent=self.page_4)
        self.output_label.setGeometry(QtCore.QRect(80, 390, 551, 121))
        self.output_label.setStyleSheet("background-color:#156082")
        self.output_label.setObjectName("output_label")
        self.output_label_2 = QtWidgets.QLabel(parent=self.page_4)
        self.output_label_2.setGeometry(QtCore.QRect(90, 140, 531, 179))
        self.output_label_2.setStyleSheet("    QLabel {\n"
"        color: #2b8b47;\n"
"        font-size: 35px;\n"
"        font-weight: bold;\n"
"        text-align: center;\n"
"    }\n"
"    QFrame {\n"
"        border: 0;\n"
"        border-bottom: 2px solid #707070;\n"
"        width: 80%;\n"
"    }\n"
"")
        self.output_label_2.setObjectName("output_label_2")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tracking_system_text_3 = QtWidgets.QLabel(parent=self.page_3)
        self.tracking_system_text_3.setGeometry(QtCore.QRect(80, 0, 541, 81))
        self.tracking_system_text_3.setStyleSheet("color: #E8E8E8;\n"
"font-family:Arial,sans-serif;\n"
" font-style: italic; \n"
"font-weight: bold;\n"
"text-decoration: none; \n"
"font-size: 32pt")
        self.tracking_system_text_3.setObjectName("tracking_system_text_3")
        self.label_4 = QtWidgets.QLabel(parent=self.page_3)
        self.label_4.setGeometry(QtCore.QRect(60, 90, 571, 301))
        self.label_4.setObjectName("label_4")
        self.confirm_button_1 = QtWidgets.QPushButton(parent=self.page_3)
        self.confirm_button_1.setGeometry(QtCore.QRect(360, 570, 171, 61))
        self.confirm_button_1.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #76B800;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #8CD800;  /* Lighter green for hover */\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #4A9B00;  /* Adjusted pressed color to a darker green */\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 25px;  /* Ensure the disabled state also has the same curvy effect */\n"
"    border: 2px solid rgb(51, 51, 51);  /* Same border color but slightly lighter green background */\n"
"    background-color: #557A00;  /* Darker green to indicate disabled state */\n"
"}\n"
"")
        self.confirm_button_1.setObjectName("confirm_button_1")
        self.device_label = QtWidgets.QLabel(parent=self.page_3)
        self.device_label.setGeometry(QtCore.QRect(70, 400, 561, 101))
        self.device_label.setStyleSheet("background-color:#156082")
        self.device_label.setObjectName("device_label")
        self.back_button_1 = QtWidgets.QPushButton(parent=self.page_3)
        self.back_button_1.setGeometry(QtCore.QRect(170, 570, 171, 61))
        self.back_button_1.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #404040;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(112,0,0);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.back_button_1.setObjectName("back_button_1")
        self.label_6 = QtWidgets.QLabel(parent=self.page_3)
        self.label_6.setGeometry(QtCore.QRect(10, 650, 101, 51))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_3)
        self.page_actions = QtWidgets.QWidget()
        self.page_actions.setObjectName("page_actions")
        self.tracking_system_text_5 = QtWidgets.QLabel(parent=self.page_actions)
        self.tracking_system_text_5.setGeometry(QtCore.QRect(80, 0, 541, 80))
        self.tracking_system_text_5.setStyleSheet("color: #E8E8E8;\n"
"font-family:Arial,sans-serif;\n"
" font-style: italic; \n"
"font-weight: bold;\n"
"text-decoration: none; \n"
"font-size: 32pt")
        self.tracking_system_text_5.setObjectName("tracking_system_text_5")
        self.label_8 = QtWidgets.QLabel(parent=self.page_actions)
        self.label_8.setGeometry(QtCore.QRect(10, 650, 101, 51))
        self.label_8.setObjectName("label_8")
        self.borrow_button = QtWidgets.QPushButton(parent=self.page_actions)
        self.borrow_button.setGeometry(QtCore.QRect(240, 190, 231, 91))
        self.borrow_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #404040;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(112,0,0);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.borrow_button.setObjectName("borrow_button")
        self.return_button = QtWidgets.QPushButton(parent=self.page_actions)
        self.return_button.setGeometry(QtCore.QRect(240, 330, 231, 91))
        self.return_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #76B800;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #8CD800;  /* Lighter green for hover */\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #4A9B00;  /* Adjusted pressed color to a darker green */\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 25px;  /* Ensure the disabled state also has the same curvy effect */\n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.return_button.setObjectName("return_button")
        self.admin_button = QtWidgets.QPushButton(parent=self.page_actions)
        self.admin_button.setGeometry(QtCore.QRect(240, 470, 231, 91))
        self.admin_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #007BFF ;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #66B2FF;  /* Lighter green for hover */\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #0056b3;  /* Adjusted pressed color to a darker green */\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 25px;  /* Ensure the disabled state also has the same curvy effect */\n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.admin_button.setObjectName("admin_button")
        self.stackedWidget.addWidget(self.page_actions)
        self.page_admin = QtWidgets.QWidget()
        self.page_admin.setObjectName("page_admin")
        self.tracking_system_text_6 = QtWidgets.QLabel(parent=self.page_admin)
        self.tracking_system_text_6.setGeometry(QtCore.QRect(80, 0, 541, 80))
        self.tracking_system_text_6.setStyleSheet("color: #E8E8E8;\n"
"font-family:Arial,sans-serif;\n"
" font-style: italic; \n"
"font-weight: bold;\n"
"text-decoration: none; \n"
"font-size: 32pt")
        self.tracking_system_text_6.setObjectName("tracking_system_text_6")
        self.label_10 = QtWidgets.QLabel(parent=self.page_admin)
        self.label_10.setGeometry(QtCore.QRect(10, 650, 101, 51))
        self.label_10.setObjectName("label_10")
        self.home_button_3 = QtWidgets.QPushButton(parent=self.page_admin)
        self.home_button_3.setGeometry(QtCore.QRect(220, 420, 271, 91))
        self.home_button_3.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #76B800;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #8CD800;  /* Lighter green for hover */\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #4A9B00;  /* Adjusted pressed color to a darker green */\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 25px;  /* Ensure the disabled state also has the same curvy effect */\n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.home_button_3.setObjectName("home_button_3")
        self.deactivate_alarm = QtWidgets.QPushButton(parent=self.page_admin)
        self.deactivate_alarm.setGeometry(QtCore.QRect(220, 250, 271, 91))
        self.deactivate_alarm.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #007BFF ;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #66B2FF;  /* Lighter green for hover */\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #0056b3;  /* Adjusted pressed color to a darker green */\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 25px;  /* Ensure the disabled state also has the same curvy effect */\n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.deactivate_alarm.setObjectName("deactivate_alarm")
        self.stackedWidget.addWidget(self.page_admin)
        self.page_password = QtWidgets.QWidget()
        self.page_password.setObjectName("page_password")
        self.label_11 = QtWidgets.QLabel(parent=self.page_password)
        self.label_11.setGeometry(QtCore.QRect(10, 650, 101, 51))
        self.label_11.setObjectName("label_11")
        self.tracking_system_text_7 = QtWidgets.QLabel(parent=self.page_password)
        self.tracking_system_text_7.setGeometry(QtCore.QRect(80, 10, 541, 80))
        self.tracking_system_text_7.setStyleSheet("color: #E8E8E8;\n"
"font-family:Arial,sans-serif;\n"
" font-style: italic; \n"
"font-weight: bold;\n"
"text-decoration: none; \n"
"font-size: 32pt")
        self.tracking_system_text_7.setObjectName("tracking_system_text_7")
        self.home_button_2 = QtWidgets.QPushButton(parent=self.page_password)
        self.home_button_2.setGeometry(QtCore.QRect(180, 630, 171, 61))
        self.home_button_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #404040;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(112,0,0);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.home_button_2.setObjectName("home_button_2")
        self.label_3 = QtWidgets.QLabel(parent=self.page_password)
        self.label_3.setGeometry(QtCore.QRect(110, 90, 491, 181))
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.page_password)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(250, 290, 211, 321))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.password_layout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.password_layout.setContentsMargins(0, 0, 0, 0)
        self.password_layout.setObjectName("password_layout")
        self.admin_submit_button = QtWidgets.QPushButton(parent=self.page_password)
        self.admin_submit_button.setGeometry(QtCore.QRect(370, 630, 171, 61))
        self.admin_submit_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #76B800;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #8CD800;  /* Lighter green for hover */\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #4A9B00;  /* Adjusted pressed color to a darker green */\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 25px;  /* Ensure the disabled state also has the same curvy effect */\n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.admin_submit_button.setObjectName("admin_submit_button")
        self.stackedWidget.addWidget(self.page_password)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tracking_system_text_2 = QtWidgets.QLabel(parent=self.page_2)
        self.tracking_system_text_2.setGeometry(QtCore.QRect(80, 0, 541, 81))
        self.tracking_system_text_2.setStyleSheet("color: #E8E8E8;\n"
"font-family:Arial,sans-serif;\n"
" font-style: italic; \n"
"font-weight: bold;\n"
"text-decoration: none; \n"
"font-size: 32pt")
        self.tracking_system_text_2.setObjectName("tracking_system_text_2")
        self.label = QtWidgets.QLabel(parent=self.page_2)
        self.label.setGeometry(QtCore.QRect(60, 90, 591, 301))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.page_2)
        self.label_2.setGeometry(QtCore.QRect(10, 650, 101, 51))
        self.label_2.setObjectName("label_2")
        self.matriculation_label = QtWidgets.QLabel(parent=self.page_2)
        self.matriculation_label.setGeometry(QtCore.QRect(70, 400, 551, 101))
        self.matriculation_label.setStyleSheet("background-color:#156082")
        self.matriculation_label.setObjectName("matriculation_label")
        self.back_button = QtWidgets.QPushButton(parent=self.page_2)
        self.back_button.setGeometry(QtCore.QRect(170, 570, 171, 61))
        self.back_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #404040;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(112,0,0);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}\n"
"")
        self.back_button.setObjectName("back_button")
        self.confirm_button = QtWidgets.QPushButton(parent=self.page_2)
        self.confirm_button.setGeometry(QtCore.QRect(360, 570, 171, 61))
        self.confirm_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 25px;  /* Increased border-radius to make the button more curvy */\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #76B800;\n"
"    font-family: \"Calibri\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;  /* Made the text bold */\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #8CD800;  /* Lighter green for hover */\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(51,51,51);\n"
"    background-color: #4A9B00;  /* Adjusted pressed color to a darker green */\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 25px;  /* Ensure the disabled state also has the same curvy effect */\n"
"    border: 2px solid rgb(51, 51, 51);  /* Same border color but slightly lighter green background */\n"
"    background-color: #557A00;  /* Darker green to indicate disabled state */\n"
"}\n"
"")
        self.confirm_button.setObjectName("confirm_button")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.htw_logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/htw-logo.png\" width=\"550\" height=\"150\"/></p></body></html>"))
        self.tracking_system_logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/tracking_system_logo.png\"width=\"350\" height=\"300\"/></p></body></html>"))
        self.tracking_system_text.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/tracking_system.png\"width=\"550\" height=\"100\"/></p></body></html>"))
        self.developerLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:700; color:#ffffff;\">Developed by <br/>Ghassen Jamoussi</span></p></body></html>"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.tracking_system_text_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/tracking_system.png\"width=\"550\" height=\"100\"/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/htw_logo_2.png\"/></p></body></html>"))
        self.back_button_2.setText(_translate("MainWindow", "Back"))
        self.home_button.setText(_translate("MainWindow", "Home"))
        self.output_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Device: </span></p><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Assigned to: </span></p></body></html>"))
        self.output_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:35pt;\">Device assigned</span></p><p align=\"center\"><span style=\" font-size:35pt;\">successfully</span></p></body></html>"))
        self.tracking_system_text_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/tracking_system.png\"width=\"550\" height=\"100\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/scan_qr_code.png\"/></p></body></html>"))
        self.confirm_button_1.setText(_translate("MainWindow", "Confirm"))
        self.device_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Display device name here</span></p></body></html>"))
        self.back_button_1.setText(_translate("MainWindow", "Back"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/htw_logo_2.png\"/></p></body></html>"))
        self.tracking_system_text_5.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/tracking_system.png\"width=\"550\" height=\"100\"/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/htw_logo_2.png\"/></p></body></html>"))
        self.borrow_button.setText(_translate("MainWindow", "Borrow"))
        self.return_button.setText(_translate("MainWindow", "Return"))
        self.admin_button.setText(_translate("MainWindow", "Admin"))
        self.tracking_system_text_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/tracking_system.png\"width=\"550\" height=\"100\"/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/htw_logo_2.png\"/></p></body></html>"))
        self.home_button_3.setText(_translate("MainWindow", "Home"))
        self.deactivate_alarm.setText(_translate("MainWindow", "Deactivate Alarm"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/htw_logo_2.png\"/></p></body></html>"))
        self.tracking_system_text_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/tracking_system.png\"width=\"550\" height=\"100\"/></p></body></html>"))
        self.home_button_2.setText(_translate("MainWindow", "Home"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/pass_submit.png\"/></p></body></html>"))
        self.admin_submit_button.setText(_translate("MainWindow", "Submit"))
        self.tracking_system_text_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/tracking_system.png\"width=\"550\" height=\"100\"/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/scan_your_student_card_using_nfc_scanner.png\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/htw_logo_2.png\"/></p></body></html>"))
        self.matriculation_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">Display student name here</span></p></body></html>"))
        self.back_button.setText(_translate("MainWindow", "Back"))
        self.confirm_button.setText(_translate("MainWindow", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
